services:
  db:
    env_file:
      - .env
    image: postgres:13.4
    ports:
      - "5432:${DATABASE_PORT}"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}


  backend:
    env_file:
      - .env
    build:
        context: ./backend/
    command: sh -c "yarn prisma generate && yarn prisma migrate dev && yarn prisma db seed && yarn start"
    volumes:
      - ./backend/:/app
      - /app/node_modules
    depends_on:
      - db
    ports:
      - "4000:4000"

  frontend:
    env_file:
      - .env
    build:
      context: ./frontend/
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    depends_on:
      - backend
    ports:
      - "3000:3000"
